### ISSUE TITLE
Builder has no attribute warn

### ISSUE THREAD

**Issue by OvalAdmin** [sphinx-contrib/sadisplay#1]
On occasion I get the error that "builder" has no attribute "warn". I'm not sure if it's just my setup or if it's that Sphinx refactored their builder somehow and there is now a discrepancy in how to invoke warning messages from the builder. This occurs in the ``html_visit`  method of `sadisp.py`. In my current setup it's tricky to setup a break point at this line to work out why it's breaking but if I get this right I will report back.

[This](https://github.com/sphinx-doc/sphinx/issues/6673) seems related.

**Comment by estin** [comment]
Hi! Please provide some environment info:
 - python version
 - sphinx version

And I will try to reproduce and fix it

**Comment by OvalAdmin** [comment]
I'm on Python 3.7.3 and using Sphinx 3.0.4. I would have posted more except it's quiet flaky when the error pops up. 

For example if my machine is low on free memory and the documentation spins up my code base to fire autodoc then I believe the SQL Alchemy connection fails, the result of that is that there a not enough connections for sadisplay to run which triggers the call to `builder.warn`. 

I had this error before and I believe I found a fix in an e-mail from the mailing list. Unfortunately at the time I did the bad thing and modified the file within `site-packages` and do not appear to have documented what I had done. I do recall that it was the call to `warn` that triggered the error though. I'll keep an eye out for when this occurs again.

**Comment by estin** [comment]
fixed.
sadisplay extension is too old and was not support sphinx 3.x version. And now it support it.
Not released on pypi. Can you take from master branch github?
Error about `warn` attribute indicate some error rendering model.
Feel free to send more bug reports, but please be patient

**Comment by flying-sheep** [comment]
can you please release this?

**Comment by estin** [comment]
done. try it https://pypi.org/project/sphinxcontrib-sadisplay/0.3.4.dev20210416/

**Comment by flying-sheep** [comment]
Thank you!
